### ISSUE TITLE
Not saving with additional parameters 

### ISSUE THREAD

**Issue by mac2net** [jawittdesigns/CMB2-Field-Type-Select2#2]
Hi

This doesn't appear to save.
Any ideas?
Cheers
Mike

I am using this array for select options:
```
$myarray = array(
'admin_bar' =>'Admin Bar',
'dashicons' =>'Dash',
);
```
Here is the field:
```
$cmb->add_field( array(
'name' => 'The Title',
'desc' => 'The description',
'id' => 'the_id',
'type' => 'select2',
'show_option_none' => true,
'default' => 'custom',
'options' => $myarray,
'select2' => array(
'multiple'=> true,
'tags' => true,
)
) );
```

**Comment by jawittdesigns** [comment]
@mac2net I made this because the select2 field addon on the CM2 page wasn't updated for three years and I wanted to use Select2 options that weren't available in that addon. After I submitted this to the CM2 project it seems the other addon was finally updated.......

So I've decided to no longer support this. I recommend using the "approved" addon.
[https://github.com/mustardBees/cmb-field-select2](https://github.com/mustardBees/cmb-field-select2)
